name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function to build and push
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          args: --source . --registry-address ghcr.io --registry-username ${{ github.actor }} --registry-secret env:GITHUB_TOKEN build publish --registry-namespace ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
